import type { Property } from "@/types/property";

export const seedProperties: Property[] = [
  {
    id: "1",
    title: "Sunlit 3BHK with Balcony Garden",
    listingType: "SALE",
    propertyType: "Apartment",
    priceInRupees: 8500000,
    areaSqft: 1450,
    locality: "Indiranagar",
    city: "Bengaluru",
    state: "Karnataka",
    bedrooms: 3,
    bathrooms: 2,
    isFeatured: true,
    coverImageUrl:
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200",
  },
  {
    id: "2",
    title: "Modern Villa Near Tech Park",
    listingType: "SALE",
    propertyType: "Villa",
    priceInRupees: 32000000,
    areaSqft: 3200,
    locality: "Hinjewadi",
    city: "Pune",
    state: "Maharashtra",
    bedrooms: 4,
    bathrooms: 4,
    isFeatured: true,
    coverImageUrl:
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=1200",
  },
  {
    id: "3",
    title: "Cozy Studio in the Heart of the City",
    listingType: "RENT",
    propertyType: "Studio",
    priceInRupees: 28000,
    priceUnit: "month",
    areaSqft: 480,
    locality: "Bandra West",
    city: "Mumbai",
    state: "Maharashtra",
    bedrooms: 1,
    bathrooms: 1,
    isFeatured: false,
    coverImageUrl:
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200",
  },
  {
    id: "4",
    title: "Spacious 2BHK with Lake View",
    listingType: "RENT",
    propertyType: "Apartment",
    priceInRupees: 42000,
    priceUnit: "month",
    areaSqft: 1100,
    locality: "Whitefield",
    city: "Bengaluru",
    state: "Karnataka",
    bedrooms: 2,
    bathrooms: 2,
    isFeatured: false,
    coverImageUrl:
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1200",
  },
  {
    id: "5",
    title: "Premium Penthouse with Skyline Views",
    listingType: "SALE",
    propertyType: "Penthouse",
    priceInRupees: 125000000,
    areaSqft: 4500,
    locality: "Worli",
    city: "Mumbai",
    state: "Maharashtra",
    bedrooms: 4,
    bathrooms: 5,
    isFeatured: true,
    coverImageUrl:
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200",
  },
  {
    id: "6",
    title: "Independent House with Private Garden",
    listingType: "SALE",
    propertyType: "Independent House",
    priceInRupees: 18500000,
    areaSqft: 2200,
    locality: "Koregaon Park",
    city: "Pune",
    state: "Maharashtra",
    bedrooms: 3,
    bathrooms: 3,
    isFeatured: false,
    coverImageUrl:
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=1200",
  },
  {
    id: "7",
    title: "Plot Ready for Construction",
    listingType: "SALE",
    propertyType: "Plot",
    priceInRupees: 6200000,
    areaSqft: 2400,
    locality: "Sarjapur Road",
    city: "Bengaluru",
    state: "Karnataka",
    isFeatured: false,
    coverImageUrl:
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1200",
  },
  {
    id: "8",
    title: "Furnished 1BHK Near Metro",
    listingType: "RENT",
    propertyType: "Apartment",
    priceInRupees: 22000,
    priceUnit: "month",
    areaSqft: 650,
    locality: "Andheri East",
    city: "Mumbai",
    state: "Maharashtra",
    bedrooms: 1,
    bathrooms: 1,
    isFeatured: false,
    coverImageUrl:
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200",
  },
];
